### ISSUE TITLE
what is the dataset in TRACE_PATH

### ISSUE THREAD

**Issue by pyjhzwh** [notem/reWeFDE#1]
Hi, I am new to Website Fingerprinting, so I am not familiar with the structure of the dataset. I wonder what file type should be in the TRACE_PATH directory. Could you give some examples of the trace dataset? Thanks a lot.

**Comment by msrocean** [comment]
Hello, it is usually the .txt file without .txt extension. You can look into the knndata.zip from Tao Wang (http://home.cse.ust.hk/~taow/wf/data/).

**Comment by pyjhzwh** [comment]
Thanks a lot!
